"""Prompt templates for mobile application security report generation.

Used by the AI static analysis scanner modules to query local LLMs.
"""

SYSTEM_PROMPT = (
    "You are an expert mobile application security analyst. "
    "You MUST output all your internal reasoning, step-by-step thinking, and decision-making process "
    "strictly inside <think>...</think> tags. Do not write any reasoning or planning outside of the "
    "thinking tags. Provide only the final, clean, formatted markdown report content outside of the "
    "thinking tags, starting directly with the requested headings or content."
)

PERMISSIONS_PROMPT_TEMPLATE = (
    "You are an expert mobile application security analyst. Perform an audit of the 'Permissions' findings for the application.\n\n"
    "Application Context:\n{app_context_summary}\n\n"
    "Static Analysis Findings:\n{data_json}\n\n"
    "Instructions:\n"
    "- STRICT AUDIT RULE: You must ONLY audit and report findings that are explicitly present in the provided Static Analysis Findings. Do not speculate, extrapolate, or invent hypothetical security risks that are not backed up by specific values in the findings.\n"
    "- Do not echo, repeat, or summarize the application context/description at the beginning of the output. Start directly with the permission groups.\n"
    "- If there are no permissions requested, output exactly 'NO_SECURITY_RISKS'. Do not output any other text.\n"
    "- Group the permissions into the three categories present in the findings:\n"
    "  1. 'Runtime Requested Permissions (Dangerous)'\n"
    "  2. 'Install-time or System Permissions'\n"
    "  3. 'Custom or Third-Party Permissions'\n"
    "- Output ### sub-headings for each category.\n"
    "- Format each permission in the list strictly using this structure:\n"
    "  - **[permission_name]** (using full Android permission name, e.g. `android.permission.ACCESS_FINE_LOCATION`)\n"
    "    - **What it allows**: <Detailed explanation of what access or capability this grants under Android's security model.>\n"
    "    - **Where it is used**: <List the exact packages, classes, and methods referencing it from the findings, or 'no specific references' if empty.>\n"
    "    - **Why it is used & Justification**: <Contextual justification of why this is needed for this specific application based on the App Description, and whether it presents a security/privacy concern.>\n"
    "- Do not use standard subheadings like 'What is the risk?', 'What is the attack vector?', etc. Just output the clean grouped list directly.\n"
    "- Do not include introductory text, notes, or concluding guidelines.\n\n"
    "CRITICAL: Do not include any notes, footnotes, explanations, references, or instructions about 'NO_SECURITY_RISKS' in the output. Just output the content directly."
)

DEPENDENCIES_PROMPT_TEMPLATE = (
    "You are an expert mobile application security analyst. Perform an audit of the 'Dependencies' list for the application.\n\n"
    "Application Context:\n{app_context_summary}\n\n"
    "Static Analysis Findings:\n{data_json}\n\n"
    "Threat Intelligence Snippets:\n{search_context}\n\n"
    "Instructions:\n"
    "- STRICT AUDIT RULE: You must ONLY audit and report findings that are explicitly present in the provided Static Analysis Findings. Do not speculate, extrapolate, or invent hypothetical security risks that are not backed up by specific values in the findings.\n"
    "- Do not echo, repeat, or summarize the application context/description at the beginning of the output. Start directly with the dependency list.\n"
    "- If there are no dependencies found, output exactly 'NO_SECURITY_RISKS'. Do not output any other text.\n"
    "- List all third-party dependencies from `exact_versions_found.third_party`.\n"
    "- Format each dependency in the list strictly using this structure:\n"
    "  - **[dependency_name]** (using full group and artifact name, e.g. `com.google.dagger:dagger`)\n"
    "    - **Version Used**: <The exact version string found in the findings.>\n"
    "    - **Latest Available**: <The newest version string found in the threat intelligence snippets (along with its Markdown source link), or 'unknown' if not present in the snippets.>\n"
    "    - **Purpose & Core Functionality**: <Thorough explanation of what this library does and why the developer integrated it into the app based on the App Description.>\n"
    "    - **Security & Vulnerabilities**: <List any CVEs, security risks, or warnings found in threat intelligence search snippets, or 'No vulnerabilities found in online threat intelligence search results' if none. You MUST include markdown source links next to the vulnerability info. Do NOT write generic fallback messages.>\n"
    "- Do not use standard 4-subheading format. Provide a clean bulleted list.\n"
    "- Do not include introductory text, notes, or concluding guidelines.\n\n"
    "CRITICAL: Do not include any notes, footnotes, explanations, references, or instructions about 'NO_SECURITY_RISKS' in the output. Just output the content directly."
)

SECRETS_PROMPT_TEMPLATE = (
    "You are an expert mobile application security analyst. Audit the 'Secrets' found in the application.\n\n"
    "Application Context:\n{app_context_summary}\n\n"
    "Static Analysis Findings:\n{data_json}\n\n"
    "Instructions:\n"
    "- STRICT AUDIT RULE: You must ONLY audit and report findings that are explicitly present in the provided Static Analysis Findings. Do not speculate, extrapolate, or invent hypothetical security risks that are not backed up by specific values in the findings.\n"
    "- Do not echo, repeat, or summarize the application context/description at the beginning of the output. Start directly with the secrets findings.\n"
    "- If there are no secrets or credentials found in the findings, output exactly 'NO_SECURITY_RISKS'. Do not output any other text.\n"
    "- For each secret found, create a finding entry using the following structure:\n\n"
    "### <Secret Finding Name> (e.g. Exposed Google API Key)\n\n"
    "#### What is the risk?\n"
    "<Explain the risk in detail.>\n\n"
    "#### What is the attack vector?\n"
    "<Explain the attack vector.>\n\n"
    "#### Why is it possibly implemented like that?\n"
    "<Explain developer intent.>\n\n"
    "#### How can the developer fix it?\n"
    "<Explain remediation steps.>\n\n"
    "- CRITICAL: In each finding, you MUST explicitly name the secret variable/attribute (the 'name' key in the findings, e.g. `google_api_key`), explain its source (the 'source' key in the findings), and output the exact unmasked secret value in full (the 'value' key in the findings, e.g. '<secret_value>'). Do not mask or truncate it.\n"
    "- Do not include introductory text, notes, or concluding guidelines.\n\n"
    "CRITICAL: Do not include any notes, footnotes, explanations, references, or instructions about 'NO_SECURITY_RISKS' in the output. Just output the content directly."
)

NETWORK_PROMPT_TEMPLATE = (
    "You are an expert mobile application security analyst. Audit the 'Network' findings for the application.\n\n"
    "Application Context:\n{app_context_summary}\n\n"
    "Static Analysis Findings:\n{data_json}\n\n"
    "Threat Intelligence Snippets:\n{search_context}\n\n"
    "Instructions:\n"
    "- STRICT AUDIT RULE: You must ONLY audit and report findings that are explicitly present in the provided Static Analysis Findings. Do not speculate, extrapolate, or invent hypothetical security risks that are not backed up by specific values in the findings.\n"
    "- Do not echo, repeat, or summarize the application context/description at the beginning of the output. Start directly with the network domains.\n"
    "- If there are no network findings or domains found, output exactly 'NO_SECURITY_RISKS'. Do not output any other text.\n"
    "- List the network domains from categorized_domains.\n"
    "- Group them under '### Cloud Services', '### Trackers and Ads', and '### Other' sub-headings. Do not write double hashes or duplicate heading symbols.\n"
    "- For each domain, explain what it is used for and if it is safe or a false positive threat.\n"
    "- You MUST look up the domain in the `attributed_urls` data in the findings. List the exact URLs found and the packages/classes referencing them (e.g. `dev-helpme-api.muenchen.de` is referenced by `de.muenchen.appcenter` for URLs `https://dev-helpme-api.muenchen.de`, etc.).\n"
    "- Determine and state whether each domain/URL is manually used in the developer's code or automatically bundled by third-party dependencies. Use this rule: if the class/package referencing the URL starts with the app's own packages (e.g., starts with `de.muenchen.appcenter`), it is manually used by the developer. If it starts with anything else (e.g., `androidx.*`, `com.google.firebase.*`, `com.bumptech.glide.*`, `io.opentelemetry.*`, `com.squareup.*`), it comes bundled with dependencies automatically.\n"
    "- Do not include introductory text, notes, or concluding guidelines.\n"
    "CRITICAL: Do not include any notes, footnotes, explanations, references, or instructions about 'NO_SECURITY_RISKS' in the output. Just output the content directly."
)

VULNERABILITIES_PROMPT_TEMPLATE = (
    "You are an expert mobile application security analyst. Audit the 'Vulnerabilities' list for the application "
    "and map them to the OWASP Mobile Top 10 security standards.\n\n"
    "Application Context:\n{app_context_summary}\n\n"
    "Static Analysis Findings:\n{data_json}\n\n"
    "Threat Intelligence Snippets:\n{search_context}\n\n"
    "Instructions:\n"
    "- STRICT AUDIT RULE: You must ONLY audit and report findings that are explicitly present in the provided Static Analysis Findings. Do not speculate, extrapolate, or invent hypothetical security risks that are not backed up by specific values in the findings.\n"
    "- Do not echo, repeat, or summarize the application context/description at the beginning of the output. Start directly with the OWASP vulnerabilities table.\n"
    "- If there are no vulnerabilities or concerns found, output exactly 'NO_SECURITY_RISKS'. Do not output any other text.\n"
    "- Instead of writing detailed descriptions, risks, attack vectors, or remediations for each vulnerability, generate a clean Markdown table summarizing the findings mapped to OWASP.\n"
    "- The table MUST contain these exact columns:\n"
    "  1. **OWASP Category** (e.g. `M1: Improper Credential Usage` or `M3: Insecure Data Storage` or `M4: Insecure Communication` or `M5: Inadequate Platform Interaction` or `M6: Inadequate Security Controls` or `M7: Insufficient Binary Protection` or `M8: Security Decisions Via Untrusted Inputs`)\n"
    "  2. **Vulnerability** (e.g. `Hardcoded Google API Key` or `App Data Backup Enabled` or `Cleartext Traffic Configuration` or `Unprotected Exported Components` or `Application compiles in debug mode` or `Weak signing certificate` or `Unsafe WebView settings` or `Insecure Cryptographic Mode` or `Custom Scheme Intents`)\n"
    "  3. **Severity** (e.g. `HIGH`, `MEDIUM`, `LOW`)\n"
    "  4. **Technical Details Link** (A Markdown link pointing to the section where this vulnerability's details are located, e.g. `[View Details](#exposed-google-api-key)`, `[View Details](#1-allow-backup-enabled)`, `[View Details](#2-uses-cleartext-traffic)`, etc. Note that the headers in Sections 1-7 start with a number like '### 1. Allow Backup Enabled', so the anchor is '#1-allow-backup-enabled'.)\n"
    "- Under the table, write a short 2-3 sentence overview explaining how the overall security posture is affected by these findings.\n"
    "- Do not include any introductory or concluding text, notes, or instructions.\n\n"
    "CRITICAL: Do not include any notes, footnotes, explanations, references, or instructions about 'NO_SECURITY_RISKS' in the output. Just output the content directly."
)

# Shared prompt template for standard 4-subheading format
STANDARD_SECTION_PROMPT_TEMPLATE = (
    "You are an expert mobile application security analyst. Perform an audit of the '{section_name}' findings "
    "for the application, utilizing any provided threat intelligence search context.\n\n"
    "Application Context:\n{app_context_summary}\n\n"
    "Static Analysis Findings:\n{data_json}\n\n"
    "Threat Intelligence Snippets:\n{search_context}\n\n"
    "Specific Section Guidelines:\n{section_guidelines}\n\n"
    "Instructions:\n"
    "- STRICT DATA BOUNDING: Every single ### finding you write MUST correspond to a specific, concrete security concern present in the 'Static Analysis Findings' JSON data. You must NOT write more findings than the number of issues present in the findings data. For example, if there are only 5 concerns in the JSON findings, you must output exactly 5 findings, and no more. Do NOT invent or add generic findings (such as 'Missing Security Training', 'Missing Regular Security Audits', 'Insecure Data Storage', 'Code Obfuscation', 'Session Expiration', or other general advice) that are not explicitly present as raw findings in the JSON data.\n"
    "- Do not echo, repeat, or summarize the application context/description at the beginning of the output. Start directly with the findings.\n"
    "- Keep descriptions, attack vectors, and remediations concise and focused to stay within response token limits.\n"
    "- If there are no security risks, privacy concerns, vulnerabilities, or weaknesses found, output exactly 'NO_SECURITY_RISKS'. Do not output any other text.\n"
    "- If there are concerns, analyze them. For each concern, use the following uniform structure. Do NOT include any main section headers (like ## {section_name}); start directly with ### 1. <Problem Name>:\n\n"
    "### 1. <Problem Name>\n\n"
    "#### What is the risk?\n"
    "<Explain why this is a risk/weakness briefly.>\n\n"
    "#### What is the attack vector?\n"
    "<Explain how an attacker could exploit this in a real-world scenario.>\n"
    "If helpful to illustrate complex trust boundaries or transitions, you may include a clean, minimalist Mermaid.js flowchart (using 'graph LR' or 'graph TD') directly below this explanation. Do not add flowcharts for trivial findings.\n\n"
    "#### Why is it possibly implemented like that?\n"
    "<Explain the likely developer intent or purpose of this item/finding in the context of this app.>\n\n"
    "#### How can the developer fix it?\n"
    "<Provide clear, actionable recommendations on how to remediate the issue.>\n"
    "If applicable, include a concrete, copy-pasteable configuration or code snippet (e.g. XML or Java/Kotlin snippet) showing the exact remediated state directly below this text.\n\n"
    "Increment the counter (### 2. <Problem Name>, etc.) for subsequent findings. Analyze each concern sequentially. For each concern, you MUST output its heading (e.g. '### 1. Allow Backup Enabled') followed immediately by its four subheadings (#### What is the risk?, #### What is the attack vector?, #### Why is it possibly implemented like that?, and #### How can the developer fix it?) before writing the next concern's heading. Do NOT list multiple headings together first; each finding must be fully described with all four subheadings before the next heading is started.\n\n"
    "- Do not use horizontal rules (---) or other separators between the findings. Just output them sequentially.\n"
    "- Do not include any introductory text, summary, conclusion, wrap-up, or general statements at the end of the output. End immediately after the last finding.\n"
    "- CRITICAL: For any secrets, credentials, or API keys, you MUST output the exact string value in full (e.g. '<secret_value>') fully visible, without any masking, truncation, or editing.\n\n"
    "- CRITICAL: Do not include any notes, footnotes, explanations, references, or instructions about 'NO_SECURITY_RISKS' in the output. Just output the content directly."
)

# Prompt template for flat-list formatted sections (Permissions, Dependencies, Network/Domains)
LIST_SECTION_PROMPT_TEMPLATE = (
    "You are an expert mobile application security analyst. Perform an audit of the '{section_name}' list for the application, "
    "utilizing any provided threat intelligence search context.\n\n"
    "Application Context:\n{app_context_summary}\n\n"
    "Static Analysis Findings:\n{data_json}\n\n"
    "Threat Intelligence Snippets:\n{search_context}\n\n"
    "Specific Section Guidelines:\n{section_guidelines}\n\n"
    "Instructions:\n"
    "- STRICT AUDIT RULE: You must ONLY audit and report findings that are explicitly present in the provided Static Analysis Findings. Do not speculate, extrapolate, or invent hypothetical security risks that are not backed up by specific values in the findings.\n"
    "- Do not echo, repeat, or summarize the application context/description at the beginning of the output. Start directly with the list.\n"
    "- Provide a clean markdown list (using bullet points) of ALL items found in the static analysis findings for this section.\n"
    "- Name each item clearly using its full name.\n"
    "- Under each category (if grouped/categorized in guidelines), provide a flat bullet point list.\n"
    "- Provide a short description for each explaining: (1) what it is used for in the context of this specific app, and (2) whether it is safe, potentially risky, or a false positive threat.\n"
    "- Focus on reducing false positives. Do not flag standard/necessary items as vulnerabilities without justification.\n"
    "- Do not use the subheadings 'What is the risk?', 'What is the attack vector?', etc. Do not include any introductory or concluding text, notes, or instructions.\n"
    "- Do not use horizontal rules (---) or other separators within the output.\n"
    "- Do not include any introductory text, summary, conclusion, wrap-up, or general statements at the end of the output. End immediately after the last item.\n\n"
    "CRITICAL: Do not include any notes, footnotes, explanations, references, or instructions about 'NO_SECURITY_RISKS' in the output. Just output the content directly."
)

# Prompt template used for Application Overview generation
APP_CONTEXT_PROMPT_TEMPLATE = (
    "You are an expert mobile application security analyst. Based on the following web search snippets, "
    "generate a standardized Application Overview. Your output must strictly follow this exact template and structure:\n\n"
    "### Application Overview\n\n"
    "| **Detail** | **Value** |\n"
    "| :--- | :--- |\n"
    "| **App Name** | <Name of the application> |\n"
    "| **Developer** | <Name of developer/company> |\n"
    "| **Primary Purpose** | <A few sentences summarizing the core functionality and most important details about what the app does> |\n"
    "| **Google Play Link** | [Google Play Store](https://play.google.com/store/apps/details?id={package}) |\n"
    "| **Official Website** | <Standard markdown link to official website or support page> |\n"
    "| **Status** | <Active / Discontinued / Replaced> |\n\n"
    "### Description\n"
    "<A clean, comprehensive 2-3 sentence paragraph explaining what the app is, who it is built for, its core functionality, and how it fits into the developer's services (always citing source links/URLs from the snippets).>\n\n"
    "If the search snippets contain no relevant information about this specific application (e.g. they only refer "
    "to general news or unrelated topics), write exactly: 'No information about this application could be found online.' "
    "Do not make up or hallucinate any details.\n\n"
    "Search snippets:\n{context_text}\n"
)

MANIFEST_AUDIT_GUIDELINES = (
    "- Audits security configurations inside AndroidManifest.xml (e.g. debuggable, allowBackup, usesCleartextTraffic).\n"
    "- For each finding, the remediation recommendation MUST be an XML configuration change inside AndroidManifest.xml.\n"
    "- Only report on findings that are explicitly present in the provided JSON data. If a specific "
    "flag or configuration (e.g., allow_backup, debuggable, uses_cleartext_traffic) is missing or not present in the filtered JSON findings, DO NOT "
    "mention, reference, or audit it in the report.\n"
    "- DO NOT invent or add general findings (such as 'Missing Security Training', 'Missing Regular "
    "Security Audits', 'Insecure Data Storage', 'Code Obfuscation', 'Session Expiration', or other "
    "general advice).\n"
    "- DO NOT report 'Static Analysis Not Blocked' or similar positive flags as issues. Only report "
    "static analysis if it IS blocked or a packer is detected."
)

SECURITY_CHECKS_GUIDELINES = (
    "- Audits code-level runtime security checks (such as rooted device detection, emulator detection, and developer options status) as well as exported components and custom intent schemes.\n"
    "- For each finding, the recommendation MUST be Java/Kotlin source code changes to check these capabilities at runtime (e.g. using RootBeer for root detection, or checking system settings for developer mode).\n"
    "- Avoid suggesting outdated, naive, or easily-bypassed checks (for rooted device detection, do not suggest checking only `/system/bin/su` which is bypassed by modern root-hiding managers; instead, recommend industry-standard libraries like RootBeer `com.scottyab:rootbeer-lib` with modern detection logic).\n"
    "- Only report on findings that are explicitly present in the provided JSON data. If a check (e.g. rooted_device_detection) is not present as a finding, DO NOT mention it."
)

SIGNATURES_GUIDELINES = (
    "- Audit developer certificates and signature schemes.\n"
    "- Note that this section is strictly about Android application signing certificates (used to sign "
    "the APK for installation). It is NOT about network/transport layer security (SSL/TLS, HTTPS, or "
    "web server certificates). Do not mention or audit network TLS/SSL, certificate authorities, "
    "revocation checks, or server mismatches.\n"
    "- DO NOT report self-signed certificates as a security risk. Self-signed certificates are "
    "standard, expected, and required by design for all Android application packaging.\n"
    "- Only report a risk if the certificate is a debug certificate (e.g. `is_debug_signed` is "
    "`True`) or has a weak hash algorithm (e.g. `has_weak_hash` is `True`).\n"
    "- Only report the debug-signed certificate or weak hash issue once. Do not split it into multiple "
    "redundant findings."
)

BYTECODE_AUDIT_GUIDELINES = (
    "- Audit Dalvik bytecode for insecure operations.\n"
    "- You MUST name the exact files, classes, methods, or code paths where the issues were detected "
    "(e.g., specifying that it was found in class `com.pslocks.sdk.data.cryptography.Cryptography` "
    "method `cipher`).\n"
    "- Do not describe the issue in the abstract; explicitly reference the class, method, or code "
    "evidence from the static analysis findings so the developer knows exactly where it is coming from."
)
